---
abstract: 'A document reader written with GTK+.'
author:
  - 'Project Renard'
build_requires:
  Data::DPath: '0'
  File::Temp: '0'
  List::AllUtils: '0'
  Test::MockModule: '0'
  Test::MockObject: '0'
  Test::Most: '0'
  URI::file: '0'
  perl: '5.010'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.010'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.007, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Renard-Curie
requires:
  Alien::MuPDF: '0.005'
  CHI: '0'
  Cairo: '0'
  Capture::Tiny: '0'
  Class::Method::Modifiers: '0'
  File::Basename: '0'
  File::Spec: '0'
  FindBin: '0'
  Function::Parameters: '0'
  Glib: '0'
  Glib::Object::Introspection: '0'
  Glib::Object::Subclass: '0'
  Gtk3: '0'
  Import::Into: '0'
  Log::Any: '0'
  Log::Any::Adapter: '0'
  Log::Any::Adapter::Base: '0'
  Log::Any::Adapter::Util: '0'
  Modern::Perl: '0'
  Module::Util: '0'
  Moo: '2.001001'
  Moo::Role: '0'
  MooX::HandlesVia: '0'
  MooX::Role::Logger: '0'
  MooX::TypeTiny: '0'
  Path::Tiny: '0'
  Return::Type: '0'
  Try::Tiny: '0'
  Type::Libraries: '0'
  Type::Library: '0.008'
  Type::Utils: '0'
  Types::Common::Numeric: '0'
  Types::Path::Tiny: '0'
  Types::Standard: '0'
  URI: '0'
  XML::Simple: '0'
  autodie: '0'
  autovivification: '0'
  custom::failures: '0'
  lib: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/project-renard/curie
  repository: https://github.com/project-renard/curie.git
version: '0.001'
x_contributors:
  - 'Chirag <chiragghanshani@gmail.com>'
  - 'Stanislav Yotov <yotov.st@gmail.com>'
  - 'Zakariyya Mughal <zaki.mughal@gmail.com>'
x_serialization_backend: 'YAML::Tiny version 1.69'
